sudo: required
services:
  - docker
language: node_js
node_js:
  - '6'
cache: yarn
env:
  global:
    - DOCKER_URL=""
    - DOCKER_REPO=kevindoveton/pfc-client
    - DOCKER_TAG=latest
    - secure: CYoOuE2OjurD4z1lzBzZvgnTbWk6NuttZajfbbGa0AG5pOYmtBWGf3dbN3xB7L23lFM0SeYFr6RfaRl6dHAWe+0NPLsJRBLVCdBpKP6NLcRxhm7Q0VrUEr+xCzV5RCFopkh9PFKNd/hLPfDXBFel8GewHEacy7NizSG0Hgs3ziXCGGxJaQxsPerJrdNvRchExLhQSMAkQvEy/RSDyo+BCjEUDs9LVs62BEd2GURTL0DsFSNQ0sK53qj6DXz4VdOxqOKGXmZXBJgtV41N5MNhBIpbeJeORc+u4IiBH5+4tkjFL66W6e1knpD3ZC6WHA0D4pQXbvNqKD+2zu10acEC6xGNyDpZYGyt4rFd0/PREw9KXOdHW17AlxE3pG6kFxC0Ks7CJkdn6De0ewUKJkxmIZHBiF94jJhGoy26WvEE65dAZjsw06/kncDr73sSN0aqf8bipNVkVkVxQI7QY2yDl+0uQLcH0YzVswYbqRWODfV0AgdQ0EgnIS/FSVVz39yK6SDF9EvCnGhmBEmtwGwnYtD+eIJQbWzLO+FdnaEBSUv1bZNTnXTr/JYZRzk9Ot5T61c/l+aQK7UPboUUEEdYroCinZLNLKyI5kZc0utj8TuH7cnwVjU2xgOP2QR2Op6n7eHxoHnjnnCGlQzaRevsfPIJTsGM+PGH6iA6odvlmpE=
    - secure: iHqGlG7bV4x0UA7i4HaZZ+JH8y9hSXMn4wKnskjJWHJ0zAlGf52OAZudjPgzPfNc0Jl4Os5hl9UEOFseb/x8/yZwBJDSzLqQmtYL9Lvht58TKvej3z3RjQhF1TXeCPrEqa3kxku+5qoD/pMMORQSjmZiY/4JJnJkO31l9maatGZWz2Sv888zdWw/b5V6f/D1LTWsRzEUJZ8RRhHo7DaFE+O+vaqNIV5ZDUi0lr0y2WeTfBltFMXaf28e6M9X0/iOoRoZWUoDyAtF3/iHxYANRk5OT/zgoBbrhG+raArtHp8VaXnNr6loFVUP1obHe3q5RctKYKg2SQLQLrPQX99iGztdKc3auvCs6I2ZDIzziVaTikA3pf457d2Q0SD7wdJ8kdG+XmK5/lhdDVvH807hDuESNzqb9pXCTjE8Ata0C4AgRpd+/tawwWTalLZ05jhFtObtI++e0u77y/bv+KF2KYNxKmPrxVJMySpzbNDzuoff2SqCb5E3/FSKKJGhxSSnEn/+gfeEzxOp4XMncGSoQanrm6sKV7nMiwQ94Hpv3/CtvEsBom0xm849zIkFT1TcDNXeo/yBlMFnOBWjd/UmLJp0xiE1QMTf5eG8KslNxbkQV6XdRMNeAgEb5NsVjv8S3J+8neiJ3NbSUkXAYKn3jPzZe02wqKH3uGdeyGYDFDc=
script:
  - NODE_ENV='production' gulp build
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker build -t $DOCKER_URL$DOCKER_REPO\:$DOCKER_TAG .; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  $DOCKER_URL docker push $DOCKER_URL$DOCKER_REPO\:$DOCKER_TAG; fi
